### ISSUE TITLE
Can Ason be designed to be inheritable and then used to support other serialization formats?

### ISSUE THREAD

**Issue by yjhmelody** [jtenner/ason#20]
Such as JSON. ASON interface may require a visitor pattern.

**Comment by yjhmelody** [comment]
If a generic parameter supports serialization of various basic types, and the specific serialization format operation is provided by the generic parameter, then I think ason can provide serialization functions for different formats

**Comment by jtenner** [comment]
There is already a custom serialization method n each class you can implement.

```ts
__asonSerialize(): StaticArray<u8>{}
__asonDeserialize(buffer: StaticArray<u8>): void {}
```

If you would like to inject your own serialization method inside ASON, it's already possible at compile time.

**Comment by yjhmelody** [comment]
I mean to replace all encoding modes, for example, JSON encoding can be implemented based on ASON

**Comment by jtenner** [comment]
The answer here is no. I suppose it might be possible to assemble things across rust or other languages using the reflection semantics I'm designing. However, as is, the algorithm is heavily coupled to the assemblyscript runtime.
